WINDOW_WIDTH = 600
WINDOW_HEIGHT = 600

SQUARE_LENGTH = 70

BOARD_WIDTH = SQUARE_LENGTH * 7
BOARD_HEIGHT = SQUARE_LENGTH * 6

PLAYER_FRAME_WIDTH = BOARD_WIDTH / 2
PLAYER_FRAME_HEIGHT = 50

player1_name = "Trinta"
player2_name = "Chris"
